### ISSUE TITLE
error when converting file, y rotation on 4 arms seems to not be exported

### ISSUE THREAD

**Issue by Aaronstar-McClure** [GloomyFolken/tcn2obj#1]
Disclaimer: i did not make this model, DarkholmeTenk did and i have linked to his repo

whenever this file is exported, it seems the four arms y rotation gets reset, here is the [tcn](https://github.com/DarkholmeTenk/TardisMod/blob/master/models/tcn/tardisConsole.tcn), and the [obj](https://github.com/DarkholmeTenk/TardisMod/blob/master/models/tcn/tardisConsole.obj)

and here are some screenshots of what it is supposed to look like, 
![good](https://user-images.githubusercontent.com/24755349/41384776-c33bb5f2-6f45-11e8-9f95-83bdfc49c268.png) (it is a bit difficult to make out because of a semi transparent piece)
and when it is converted 
![bad](https://user-images.githubusercontent.com/24755349/41384854-38ee0cdc-6f46-11e8-93be-5fcd8771c16b.png) (again, max does not understand the partially transparent piece, but that is fixable)

**Comment by GloomyFolken** [comment]
I believe it applies rotations in the wrong order. I'll check this out since someone still needs this tool :D

**Comment by GloomyFolken** [comment]
Fixed.
